# Generated by Django 3.1.7 on 2021-03-10 01:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('photo', models.IntegerField(default=13)),
                ('keywords', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateForms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameform', models.CharField(blank=True, max_length=250)),
                ('coreform', models.CharField(blank=True, max_length=9000)),
                ('description', models.CharField(blank=True, max_length=9000)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.IntegerField(blank=True, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('thematique', models.CharField(max_length=30)),
                ('remuneration', models.CharField(max_length=40)),
                ('description', ckeditor.fields.RichTextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('ville', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/mission_logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=250)),
                ('nameform', models.CharField(blank=True, max_length=250)),
                ('date', models.CharField(blank=True, max_length=250)),
                ('data', models.JSONField(blank=True, max_length=9000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visite_status', models.IntegerField(choices=[('0', 'Pending'), ('1', 'Accepter'), ('2', 'refuser')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enqueteur.mission')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='organisme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enqueteur.organisme'),
        ),
        migrations.AddField(
            model_name='mission',
            name='questionnaire',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='enqueteur.createforms'),
        ),
        migrations.CreateModel(
            name='Enqueteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=20, null=True)),
                ('genre', models.CharField(max_length=25, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('birth_day', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.CharField(blank=True, max_length=250)),
                ('ordinateur', models.CharField(blank=True, choices=[('1', 'oui'), ('2', 'non')], max_length=25)),
                ('vehicule', models.CharField(blank=True, choices=[('1', 'oui'), ('2', 'non')], max_length=25)),
                ('userexpen', models.CharField(blank=True, max_length=40, null=True)),
                ('userexp', models.CharField(blank=True, max_length=40, null=True)),
                ('expmois', models.CharField(blank=True, choices=[('1', 'Entre 0 et 3'), ('2', 'Entre 3 et 6'), ('3', 'Plus de 6')], max_length=25, null=True)),
                ('societe', models.CharField(blank=True, max_length=40, null=True)),
                ('lunettes', models.CharField(blank=True, choices=[('1', 'oui'), ('2', 'non')], max_length=25, null=True)),
                ('logement', models.CharField(blank=True, choices=[('1', 'Proprietaire'), ('2', 'locataire')], max_length=40, null=True)),
                ('habitation', models.CharField(blank=True, choices=[('1', 'Maison'), ('2', 'Appartement'), ('3', 'Villa'), ('4', 'Lotissement'), ('5', 'Autre')], max_length=40, null=True)),
                ('langues', models.CharField(blank=True, max_length=40, null=True)),
                ('meilleur', models.CharField(blank=True, max_length=40, null=True)),
                ('pire', models.CharField(blank=True, max_length=40, null=True)),
                ('restaurant', models.CharField(blank=True, choices=[('1', 'Entre 0 et 3'), ('2', 'Entre 3 et 6'), ('3', 'Plus de 6')], max_length=25, null=True)),
                ('situation', models.CharField(blank=True, max_length=40, null=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('joindre', models.CharField(blank=True, choices=[('1', '8h00 - 12h00'), ('2', '12h00 - 14h00'), ('3', '14h00 - 17h00')], max_length=25, null=True)),
                ('enfants', models.CharField(blank=True, choices=[('1', 'Entre 0 et 3'), ('2', 'Entre 3 et 6'), ('3', 'Plus de 6')], max_length=25, null=True)),
                ('status', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='createforms',
            name='organisme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enqueteur.organisme'),
        ),
        migrations.CreateModel(
            name='Contact_enqueteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enqueteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enqueteur.enqueteur')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enqueteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enqueteur.enqueteur')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidature_status', models.IntegerField(choices=[('0', 'Pending'), ('1', 'Accepter'), ('2', 'refuser')], default=0)),
                ('motivation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enqueteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enqueteur.enqueteur')),
                ('mission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enqueteur.mission')),
            ],
        ),
    ]
