# Generated by Django 3.1.7 on 2021-03-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createforms',
            name='organisme',
        ),
    ]
