# Generated by Django 3.1.7 on 2021-02-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0002_auto_20210223_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enqueteur',
            name='experience',
        ),
    ]
