# Generated by Django 3.1.7 on 2021-03-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0002_organisme_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='Nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mission',
            name='remuneration',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mission',
            name='thematique',
            field=models.CharField(max_length=30),
        ),
    ]
