# Generated by Django 3.1.7 on 2021-03-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0003_auto_20210310_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteur',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
