# Generated by Django 3.1.7 on 2021-03-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0003_auto_20210302_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisme',
            old_name='Nom',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='mission',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enqueteur.createforms'),
        ),
    ]
