# Generated by Django 3.1.7 on 2021-02-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0004_auto_20210223_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteur',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='user/photos/'),
        ),
    ]
