# Generated by Django 3.1.7 on 2021-03-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0004_auto_20210310_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='avergedata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namemission', models.CharField(blank=True, max_length=250)),
                ('averges', models.JSONField(blank=True, max_length=9000, null=True)),
            ],
        ),
    ]
