# Generated by Django 3.1.7 on 2021-03-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0005_auto_20210302_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisme',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='content_file_name'),
        ),
    ]
