# Generated by Django 3.1.7 on 2021-03-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0006_auto_20210302_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisme',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/mission_logo'),
        ),
    ]
