# Generated by Django 3.1.7 on 2021-03-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_enqueteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enqueteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enqueteur.enqueteur')),
            ],
        ),
    ]
