# Generated by Django 3.1.7 on 2021-03-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0009_auto_20210318_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteur',
            name='verification',
            field=models.CharField(blank=True, choices=[('0', 'unchecked'), ('1', 'verified'), ('2', 'refused')], default=0, max_length=25),
        ),
    ]
