# Generated by Django 3.1.7 on 2021-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0010_auto_20210318_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteur',
            name='verification',
            field=models.IntegerField(),
        ),
    ]
