# Generated by Django 3.1.7 on 2021-03-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0014_auto_20210324_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteur',
            name='birth_day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enqueteur',
            name='profile_pic',
            field=models.FileField(blank=True, default='static/dist/img/AdminLTELogo.png', upload_to=''),
        ),
    ]
