# Generated by Django 3.1.7 on 2021-03-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0015_auto_20210326_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='date_visite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
