# Generated by Django 3.1.7 on 2021-03-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0016_candidature_date_visite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='candidature_status',
            field=models.IntegerField(choices=[('0', 'Pending'), ('1', 'Accepter'), ('2', 'refuser'), ('3', 'new')], default=3),
        ),
    ]
