# Generated by Django 3.1.7 on 2021-03-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0017_auto_20210331_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='candidature_status',
            field=models.IntegerField(choices=[('0', 'Pending'), ('1', 'Accepter'), ('2', 'refuser')], default=0),
        ),
    ]
