# Generated by Django 3.1.7 on 2021-04-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0021_auto_20210331_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createforms',
            name='coreform',
            field=models.CharField(blank=True, max_length=900000),
        ),
    ]
