# Generated by Django 3.1.7 on 2021-04-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0022_auto_20210405_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='createforms',
            name='breifing',
            field=models.FileField(blank=True, upload_to='enqueteur/templates/EnqueteurPage/breifing'),
        ),
    ]
