# Generated by Django 3.1.7 on 2021-04-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0023_createforms_breifing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createforms',
            name='breifing',
            field=models.FileField(blank=True, upload_to='media/mission_logo'),
        ),
    ]
