# Generated by Django 3.1.7 on 2021-04-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0024_auto_20210408_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteur',
            name='telephone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
