# Generated by Django 3.1.7 on 2021-05-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0025_auto_20210419_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remuneration_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_survey', models.CharField(max_length=1000000, null=True)),
                ('mission_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date_envoie', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(choices=[('0', 'En cours'), ('1', 'Payer'), ('2', 'refuser')], default=0)),
                ('remuneration', models.CharField(blank=True, max_length=100, null=True)),
                ('enqueteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enqueteur.enqueteur')),
            ],
        ),
    ]
