# Generated by Django 3.1.7 on 2021-06-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0027_auto_20210609_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, max_length=9000, null=True)),
                ('enqueteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enqueteur.enqueteur')),
            ],
        ),
    ]
