# Generated by Django 3.1.7 on 2021-06-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0028_handicap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteur',
            name='meilleur',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='enqueteur',
            name='pire',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
