# Generated by Django 3.1.7 on 2021-11-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enqueteur', '0029_auto_20210617_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enqueteur',
            name='userexpen',
        ),
        migrations.AlterField(
            model_name='enqueteur',
            name='habitation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
